
server:
  servlet:
    context-path: /api

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration
  application:
    name: CACHE-DEMO
  profiles:
    active:
    - local

resilience4j:
  circuitbreaker:
    instances:
      userService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        wait-duration-in-open-state: 5s
        sliding-window-type: COUNT_BASED

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

pagesearch:
  page: 0
  limit: 25